apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcation-example 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: muralisocial123/transcation-bank-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: TITLE
          value: "NGINX APP1"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx  
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3000
  selector:
    app: nginx
